version: 2.1

orbs:
    node: circleci/node@4.5.1

jobs:
    build_dev:
        docker:
            - image: cimg/node:10.19.0
        steps:
            - checkout
            - node/install-packages
            - run:
                  name: Install AWS CLI
                  command: sudo apt-get update && sudo apt install -y python3-pip && sudo pip3 install awscli --upgrade
            - run:
                  name: Build project
                  command: npm run-script build
            - run:
                  name: Deploy project in dev
                  command: npm run deploy

    build_prod:
        docker:
            - image: cimg/node:10.19.0
        steps:
            - checkout
            - node/install-packages
            - run:
                  name: Install AWS CLI
                  command: sudo apt-get update && sudo apt install -y python3-pip && sudo pip3 install awscli --upgrade
            - run:
                  name: Build the project
                  command: npm run-script build
            - run:
                  name: Deploy project in production
                  command: npm run release

workflows:
    version: 2
    PORTFOLIO_CI_CD:
        jobs:
            - build_dev:
                  filters:
                      branches:
                          only: dev

            - build_prod:
                  filters:
                      branches:
                          only: master
